import type { Debt, Expense, FinancialGoal } from "../types/finance";

export const INITIAL_EXPENSES: Expense[] = [
  {
    id: 1,
    amount: 100,
    category: "family",
    mood: "happy",
    date: "01.04.2026",
    note: "Anaya",
    recurring: false,
  },
  {
    id: 2,
    amount: 100,
    category: "transport",
    mood: "happy",
    date: "03.04.2026",
    note: "Aylıq nəqliyyat",
    recurring: true,
  },
  {
    id: 3,
    amount: 200,
    category: "tech",
    mood: "excited",
    date: "05.04.2026",
    note: "Airpods",
    recurring: false,
  },
  {
    id: 4,
    amount: 10,
    category: "personal",
    mood: "happy",
    date: "07.04.2026",
    note: "Bərbər",
    recurring: false,
  },
  {
    id: 5,
    amount: 6,
    category: "housing",
    mood: "happy",
    date: "10.04.2026",
    note: "Komunal — su",
    recurring: true,
  },
  {
    id: 6,
    amount: 27,
    category: "housing",
    mood: "happy",
    date: "10.04.2026",
    note: "Komunal — qaz",
    recurring: true,
  },
  {
    id: 7,
    amount: 86,
    category: "housing",
    mood: "happy",
    date: "10.04.2026",
    note: "Komunal — işıq+internet",
    recurring: true,
  },
  {
    id: 8,
    amount: 30,
    category: "relationship",
    mood: "happy",
    date: "12.04.2026",
    note: "Sevgiliyə",
    recurring: false,
  },
  {
    id: 9,
    amount: 160,
    category: "gold",
    mood: "happy",
    date: "15.04.2026",
    note: "Qızıl alışı",
    recurring: false,
  },
  {
    id: 10,
    amount: 20,
    category: "invest",
    mood: "happy",
    date: "16.04.2026",
    note: "İnvestisiya (70-50)",
    recurring: false,
  },
  {
    id: 11,
    amount: 500,
    category: "forex",
    mood: "happy",
    date: "20.04.2026",
    note: "Euro alışı",
    recurring: false,
  },
  {
    id: 12,
    amount: 50,
    category: "savings",
    mood: "happy",
    date: "22.04.2026",
    note: "Əlavə yığım",
    recurring: false,
  },
];

export const INITIAL_DEBTS: Debt[] = [
  {
    id: 1,
    name: "Jhon",
    amount: 100,
    type: "lent",
    date: "08.04.2026",
    note: "Borc verdim",
    paid: false,
  },
];

export const INITIAL_GOALS: FinancialGoal[] = [
  {
    id: 1,
    name: "Ev üçün ilkin ödəniş",
    target: 30000,
    saved: 2400,
    emoji: "🏠",
  },
  { id: 2, name: "Təhsil / Kurslar", target: 2000, saved: 350, emoji: "🎓" },
  { id: 3, name: "Səyahət fondu", target: 3000, saved: 600, emoji: "✈️" },
];
