import type { MonthHistory } from "../types/finance";

export const MONTHLY_HISTORY: MonthHistory[] = [
  {
    month: "Yanvar",
    year: 2026,
    income: 1800,
    expenses: [
      { category: "housing", amount: 320 },
      { category: "food", amount: 280 },
      { category: "transport", amount: 90 },
      { category: "personal", amount: 15 },
      { category: "entertainment", amount: 120 },
      { category: "clothing", amount: 85 },
      { category: "relationship", amount: 50 },
      { category: "gold", amount: 100 },
      { category: "forex", amount: 200 },
      { category: "savings", amount: 150 },
    ],
  },
  {
    month: "Fevral",
    year: 2026,
    income: 1800,
    expenses: [
      { category: "housing", amount: 315 },
      { category: "food", amount: 260 },
      { category: "transport", amount: 95 },
      { category: "health", amount: 40 },
      { category: "personal", amount: 10 },
      { category: "entertainment", amount: 90 },
      { category: "gifts", amount: 150 },
      { category: "tech", amount: 120 },
      { category: "relationship", amount: 80 },
      { category: "gold", amount: 120 },
      { category: "forex", amount: 150 },
      { category: "savings", amount: 100 },
    ],
  },
  {
    month: "Mart",
    year: 2026,
    income: 1800,
    expenses: [
      { category: "housing", amount: 325 },
      { category: "food", amount: 300 },
      { category: "transport", amount: 100 },
      { category: "family", amount: 50 },
      { category: "personal", amount: 10 },
      { category: "entertainment", amount: 75 },
      { category: "hobby", amount: 60 },
      { category: "clothing", amount: 100 },
      { category: "gold", amount: 140 },
      { category: "forex", amount: 300 },
      { category: "invest", amount: 50 },
      { category: "savings", amount: 80 },
    ],
  },
];
